#!/bin/bash

export GOPATH=$GOPATH:`pwd`

echo "build/install router pkg and test"
go install router
go test router
echo "build/install test cases"
go install tests
echo "build/install chat server and client"
go install apps/chat/chatcli
go install apps/chat/chatsrv
echo "build/install ping pong games..."
go install apps/pingpong/game1
go install apps/pingpong/game2
go install apps/pingpong/game3
go install apps/pingpong/game4
go install apps/pingpong/game5
go install apps/pingpong/game6
echo "build/install dummy server and client"
go install apps/dummyserver/client
go install apps/dummyserver/server



